### ISSUE TITLE
Using in conjunction with standard data-bind

### ISSUE THREAD

**Issue by JD-Robbs** [rniemeyer/knockout-classBindingProvider#22]
Hi there,

I'm really loving this! In the past I tended to create custom bindings whenever I apply more than two or three bindings and then move them to JS that way (i.e. using ko.applyBindingsToNode).

However, I wonder if it would be at all possible to still keep using `data-bind` _as well as_ `data-class`?  That would save you from having to keep creating new items on the binding class for trivial things like `text: name`.

Anyway, great plugin and thanks for sharing! :smiley:

**Comment by rniemeyer** [comment]
@JD-Robbs - there is an option you can pass when installing to plugin to fall back to `data-bind`. It would look like: 

`ko.bindingProvider.instance = new ko.classBindingProvider(bindings, { fallback: true });`

Hope that helps!

**Comment by JD-Robbs** [comment]
Oops, sorry about this - I didn't realise it was a feature already. Thanks a bunch - this is amazing! :smiley:
