### ISSUE TITLE
view model doesn't update when textInput changes

### ISSUE THREAD

**Issue by mrkos67** [rniemeyer/knockout-classBindingProvider#27]
fiddle: http://jsfiddle.net/6qvsth12/2/

as you can see, when making changes to the first input (the old data-bind attribute), textInput correctly updates the view model variable. updating the second input does not update the view model variable.

**Comment by mbest** [comment]
For a two-way binding, the binding handler needs to receive the observable, not just the value.

    return {
        textInput: this.code
    }

http://jsfiddle.net/6qvsth12/3/

**Comment by mrkos67** [comment]
those pesky parentheses. thanks!

**Comment by rniemeyer** [comment]
thanks for jumping in @mbest 👍
